### R

In [4]:
print(4*1:10) ## vector 기반 데이터 저장 방식
print(2^2:3)

 [1]  4  8 12 16 20 24 28 32 36 40
[1] 4 3


In [5]:
2^2:3  ## ??? 순서가 바뀌었나봄

[1] 4 3

In [10]:
5 > 3 && 3 > 4  ## 그냥 &도 됨, C에서 가져온듯?

[1] FALSE

In [11]:
ex = 1:10
1 < ex  ## 벡터와 스칼라가 만나면, 스칼라를 벡터로 변환

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [17]:
ex > 8 & ex < 2  ## &&은 안되네 여긴 왜

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

`-` 객체 종류 및 값 지정

In [36]:
# Numeric : int / float
print(paste(mode(1), mode(1.1)))
# Character : string
print(class("abc"))
# Logical : bool
print(class(T))
# Vector : list
print(c(1,2,3))
# Factor, 순서형
print(class(as.factor(1:2)))
# Nan
print(0/0)
# Inf
print(1/0)

[1] "numeric numeric"
[1] "character"
[1] "logical"
[1] 1 2 3
[1] "factor"
[1] NaN
[1] Inf


`-` 객체 종류 및 값 지정

In [37]:
c("T", F)  ## 서로 다른 값을 넣으면 하나로 병합됨

[1] "T"     "FALSE"

In [38]:
c(as.factor(2), 3)

[1] 1 3

> 문자 > 수치 / 논리 > factor

In [40]:
1:3 + 1:40  ## 짧은 쪽을 늘린다.

Warning message in 1:3 + 1:40:
“longer object length is not a multiple of shorter object length”


[1]  2  4  6  5  7  9  8 10 12 11 13 15 14 16 18 17 19 21 20 22 24 23 25 27 26
[26] 28 30 29 31 33 32 34 36 35 37 39 38 40 42 41

> 일반 문자 $\to$ 숫자 (X)
>
> 숫자로 된 문자 $\to$ 숫자 (O)
>
> 숫자 $\to$ 문자 (O)
>
> 논리 $\to$ 숫자 (O)

In [42]:
as.character(as.factor(2:3))

[1] "2" "3"

In [43]:
as.numeric(as.factor(2:3))  ## 순서형 자료라 인덱스 반환

[1] 1 2

`-` 벡터 및 행렬연산

In [45]:
a = c(2,3,6)
which(a > 3)  ## index

[1] 3

In [46]:
a[which(a < 4)] = 0  ## 벡터 우선 연산
a

[1] 0 0 6

`-` matrix

In [8]:
A = matrix(1:40, 2, 20, byrow = TRUE)  ## 디폴트는 열단위로 집어넣음(시리즈로)
A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,]  1    2    3    4    5    6    7    8    9   10    11    12    13    14   
[2,] 21   22   23   24   25   26   27   28   29   30    31    32    33    34   
     [,15] [,16] [,17] [,18] [,19] [,20]
[1,] 15    16    17    18    19    20   
[2,] 35    36    37    38    39    40

In [5]:
matrix(c(2, 4), 2,2)  ## 차수가 벡터의 차수의 배수라면 원소의 수가 적어도 넣을 수 있음(벡터연산과 동일)

[,1] [,2]
[1,] 2    2   
[2,] 4    4

In [10]:
print(dim(A), diag(A))

[1]  2 20


[1]  1 22

`-` matrix에 `which()`를 쓰면

In [12]:
which(A <= 20)

[1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39

> 위에서 아래로 넣었다고 간주하여 연산한다.

In [22]:
A[which(A <= 20)]  ## 왠만해선 matrix 전체를 대상으로 which문은 사용하지 마세요.

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [26]:
set.seed(111)
a = matrix(rnorm(100), 10, 10)
aa = a[c(4,5), 1:5]; aa

[,1]      [,2]      [,3]       [,4]      [,5]     
[1,] -2.302346 0.3940541 -0.1595768 -1.620470 0.4811246
[2,] -0.170876 0.7975285  0.3265492 -2.265996 0.7419716

In [27]:
t(aa) ## transpose

[,1]       [,2]      
[1,] -2.3023457 -0.1708760
[2,]  0.3940541  0.7975285
[3,] -0.1595768  0.3265492
[4,] -1.6204700 -2.2659960
[5,]  0.4811246  0.7419716

In [28]:
aa %*% t(aa)

[,1]     [,2]    
[1,] 8.338943 4.684535
[2,] 4.684535 6.457144

In [36]:
set.seed(111)
A = matrix(rnorm(16), 4,4)
solve(A)

[,1]      [,2]      [,3]       [,4]     
[1,]  4.808390 -9.788799 -2.6991982  1.828429
[2,] -2.238740  4.886830  0.7409947 -1.031018
[3,] -6.910127 12.327412  3.9774536 -3.015182
[4,] -3.829393  8.035072  2.4566288 -1.877991

`-` solve()는 Ax = b에서 x의 해를 내놓는 함수임.

In [37]:
b = c(1,2,3,4)
solve(A, b)

[1] -15.553088   5.633832  17.616329  12.098675

In [38]:
A = matrix(c(2,3,3,6),2,2)
B = matrix(c(2,7,6,3,5,4), 2,3)
A*B  ## 아예 안됨, 굳

ERROR: Error in A * B: non-conformable arrays


`-` 배열

In [39]:
a = array(1:12, c(3,2,2))
class(a); mode(a)

[1] "array"

[1] "numeric"

In [40]:
print(a)

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12



> 행렬 구조를 유지하고자 함.

행렬과 배열은 모든 원소의 자료형이 동일해야 한다. 따라서 각 열의 자료형을 유지시키기 위해 데이터프레임을 사용해야 한다.

R의 경우 정수(integer)를 입력해도 기본적으로 실수(double)로 받아들인다.

In [44]:
a = c(2,3,4)
b = paste('a', 1:3, sep = "")
df = data.frame(a,b)
print(df)

  a  b
1 2 a1
2 3 a2
3 4 a3


In [47]:
mode(df)

[1] "list"

> 데이터프레임은 리스트의 특별한 유형이라고 볼 수 있다. (Json 파일 구조 / dictionary 구조와 유사)

`-` `list` : 원소가 벡터만이 아닌 다른 어떤 것이든 가능

In [49]:
a = c(2,3,4)
A = matrix(1:4, 2,2)
lst_a = list(a, A)  ## 벡터와 데이터프레임이 들어가있음
lst_a

[[1]]
[1] 2 3 4

[[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

In [51]:
lst_b = list(lst_a, c("w", "e", "f"))

`-` 자료형 변환

In [52]:
aa = "ahhhh i wanna go home"
as.numeric(aa)
as.character(23)
as.double(3)
as.list(rep(1,2))
as.data.frame(A)

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”


[1] NA

[1] "23"

[1] 3

[[1]]
[1] 1

[[2]]
[1] 1

V1 V2
1 1  3 
2 2  4

In [53]:
a = 1:10
length(a)  ## 데이터프레임이나 행렬의 경우 총 원소의 개수

[1] 10

In [54]:
print(rep(c("a", "b"), c(1,3)))
print(rep(c("a", "b"), each = 2))  ## 각각 2회
print(rep(c("a", "b"), 2))  ## 앞의 것을 2회 반복

[1] "a" "b" "b" "b"
[1] "a" "a" "b" "b"
[1] "a" "b" "a" "b"


In [56]:
seq(0, 10, length = 11)

[1]  0  1  2  3  4  5  6  7  8  9 10

In [ ]:
v = data.frame(a=a, b=b)

`-` `rbind`, `cbind`, `merge`

In [60]:
a = matrix(1:10, 5,2)
b = 1:5

bb = rbind(a,b)
bb

Warning message in rbind(a, b):
“number of columns of result is not a multiple of vector length (arg 2)”


[,1] [,2]
  1     6  
  2     7  
  3     8  
  4     9  
  5    10  
b 1     2

In [61]:
unique(bb)  ## 튜플의 유일성을 확인하는 구문, 중복을 없애줌

[,1] [,2]
  1     6  
  2     7  
  3     8  
  4     9  
  5    10  
b 1     2

In [63]:
cust_mart_7 <- data.frame(cust_id = c("c03", "c04", "c05", "c06"), buy_cnt = c(3,1,4,1))
cust_mart_6 <- data.frame(cust_id = c("c04", "c05", "c06", "c07"), buy_cnt = c(3,2,1,3))

merge(cust_mart_6, cust_mart_7, by = "cust_id")  ## pd.merge()

cust_id buy_cnt.x buy_cnt.y
1 c04     3         1        
2 c05     2         4        
3 c06     1         1

In [64]:
merge(cust_mart_6, cust_mart_7, by = "cust_id", all.x = TRUE, all.y = TRUE)  ## 전체 외부조인

cust_id buy_cnt.x buy_cnt.y
1 c03     NA         3       
2 c04      3         1       
3 c05      2         4       
4 c06      1         1       
5 c07      3        NA

> x만 살리면 왼쪽 외부조인 / y만 살리면 오른쪽 외부조인