### Python basics & Packages

In [1]:
print("hello world")

hello world


In [2]:
3.0 + 5

8.0

> 실수형과 정수형이 같이 연산되면 실수형으로 반환

In [6]:
print(int(1.4 + 7), int(1.6 + 7))

8 8


> 실수형으로 반환된 것을 내려서 정수형으로 변환(가우스기호)

In [7]:
4/2

2.0

> 나눗셈 연산은 자동으로 실수형으로 변환

In [8]:
round(2.0012, 2)

2.0

> 반올림

In [10]:
print("vb_" + "3")

vb_3


> 문자의 합은 결합

In [13]:
print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")  ## 주석처리에서도 용이

Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to



In [14]:
a = 'abv'
a[2]

'v'

> 문자열은 각각의 인덱스를 가지고 있음. 슬라이싱, 스트라이딩 다 가능

In [17]:
str = "a zip gago sipda"
print(str[0:2])
print(str[-1])  ## last words
print(str[0:6:2])  ## striding

a 
a
azp


In [20]:
len(str)

16

In [21]:
print(str[16])

IndexError: string index out of range

In [22]:
str[0] = "a"

TypeError: 'str' object does not support item assignment

> 문자열에 개별 단위로 값을 집어넣을 수는 없음. 어케하더라.

In [24]:
[3,4,5] + [2,4]  ## 리스트의 합은 스택을 더 쌓는 거

[3, 4, 5, 2, 4]

In [26]:
v = [3,4,5]
v.append(4); v  ## append()보다 초기화하고 인덱스에 값을 넣어주는 것이 더 연산이 빠름(가능한 경우에)

[3, 4, 5, 4]

In [27]:
a = ['f', 'h', 'j']
n = [1,2,3]
x = [a, n]  ## double list
print(x)

[['f', 'h', 'j'], [1, 2, 3]]


In [42]:
a = ['f', 'h', 'j']
a[0] = []
a

[[], 'h', 'j']

In [43]:
a[0:1] = []
a

['h', 'j']

> 순열로 잡은 경우 내용을 삭제.

In [45]:
b = list(range(20))
b[0:5] = []

In [46]:
b

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [28]:
import numpy as np

In [32]:
a = np.linspace(2, 3, 30)
a

array([2.        , 2.03448276, 2.06896552, 2.10344828, 2.13793103,
       2.17241379, 2.20689655, 2.24137931, 2.27586207, 2.31034483,
       2.34482759, 2.37931034, 2.4137931 , 2.44827586, 2.48275862,
       2.51724138, 2.55172414, 2.5862069 , 2.62068966, 2.65517241,
       2.68965517, 2.72413793, 2.75862069, 2.79310345, 2.82758621,
       2.86206897, 2.89655172, 2.93103448, 2.96551724, 3.        ])

In [33]:
a[np.where(np.linspace(2, 3, 30) >= 2.5)]

array([2.51724138, 2.55172414, 2.5862069 , 2.62068966, 2.65517241,
       2.68965517, 2.72413793, 2.75862069, 2.79310345, 2.82758621,
       2.86206897, 2.89655172, 2.93103448, 2.96551724, 3.        ])

In [49]:
a = np.array([[[2]]])
a.shape

(1, 1, 1)

In [50]:
np.array([2,3,4]).shape

(3,)

In [52]:
np.array([[2,3,7],[4,5,6]]).shape

(2, 3)

In [55]:
a = np.array([[2,3,7],[4,5,6]]);a

array([[2, 3, 7],
       [4, 5, 6]])

* 배열을 슬라이싱

In [56]:
print(a[0, 0:2])

[2 3]


In [63]:
a = np.linspace(2, 3, 30)
print(np.where(a >= 2.5)[0])  ## numpy array에서 리스트를 추출할 수 있음

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [61]:
a[np.where(a >= 2.5)]

array([2.51724138, 2.55172414, 2.5862069 , 2.62068966, 2.65517241,
       2.68965517, 2.72413793, 2.75862069, 2.79310345, 2.82758621,
       2.86206897, 2.89655172, 2.93103448, 2.96551724, 3.        ])

In [64]:
a = np.array([[[2,3,4],[5,6,7]],[[2,3,4],[6,8,9]]])
print(a[1])
print(a.shape)
print(a[1,1,:])

[[2 3 4]
 [6 8 9]]
(2, 2, 3)
[6 8 9]


In [72]:
np.zeros(2); np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
a = np.array([3,2,4,5])
a.sort()
print(a)

[2 3 4 5]


In [121]:
a = [6,5,4,3]
np.argsort(a)  ## sorting을 하기 위한 index

array([3, 2, 1, 0])

In [94]:
a[np.argsort(a)]  ## 그냥 컴프리헨션 하자...

TypeError: only integer scalar arrays can be converted to a scalar index

In [97]:
a = np.ones(3)
b = np.array([2, 4, 6])
print(np.concatenate((a, b), axis = 0))

[1. 1. 1. 2. 4. 6.]


In [104]:
np.stack((a, b), axis = 0)

array([[1., 1., 1.],
       [2., 4., 6.]])

In [105]:
a = np.append(a, 3)

In [107]:
a.shape

(4,)

In [139]:
np.reshape([1,2,3,4], (2,2))  ## 행단위로 넣는 게 default. 애초에 이쪽이 연산이 쉬움

array([[1, 2],
       [3, 4]])

In [119]:
np.reshape([1,2,3,4], (2,2), order = "F")

array([[1, 3],
       [2, 4]])

차원의 개수 / 원소의 개수 / 차원 벡터

In [128]:
a = np.ones(3)
a = np.append(a,3)
print(a.shape)
a = np.reshape(a, (2,2))
print(a.shape)
b = np.array([[1,3],[3,4]])

(4,)
(2, 2)


In [132]:
v = np.concatenate((a, b), axis = 1)
print(v.ndim)
print(v.size)
print(v.shape)

2
8
(2, 4)


In [134]:
v = np.array([3,4,5])
print(v.shape)
vv = np.array([[3], [4], [5]])
print(vv.shape)

(3,)
(3, 1)


np.array operation

In [135]:
np.array([3]) + np.array([[3]])  ## shape이 안맞아도 그냥 연산이 됨

array([[6]])

In [136]:
np.array([3,4]) + np.array([[3,4]])

array([[6, 8]])

In [138]:
a[np.newaxis, :]  ## instance

array([[[1., 1.],
        [1., 3.]]])

> `np.newaxis`라는 인스턴스는 새로운 축 자체를 의미

* 차원을 바꿀 때 행이나 열 단위 지정을 하는 옵션

In [141]:
aa = np.array([[1,2,3,4], [5,6,7,8], [3,5,7,9]])
print(aa)
print(aa[aa < 4])  ## 인덱스를 연산했을 때 차원이 달라짐.

[[1 2 3 4]
 [5 6 7 8]
 [3 5 7 9]]
[1 2 3 3]


In [145]:
(aa > 3) & (aa < 5)

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [146]:
a = np.array([[2,3],[1,2]])
b = np.array([[1,4],[2,6]])
c = np.vstack([a,b])
print(c)  ## np.concatenate((a, b), axis = 0)
print(np.hstack([a,b]))  ## np.concatenate((a, b), axis = 1)

[[2 3]
 [1 2]
 [1 4]
 [2 6]]
[[2 3 1 4]
 [1 2 2 6]]


배열을 쪼개는 함수

In [151]:
cc = np.arange(30).reshape(5,6)
print(cc)
nn = np.hsplit(cc, 2)
print(nn)  ## 클래스가 두 개 들어가있는 이상한 구조
print(nn[0])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26]]), array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])]
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]
 [24 25 26]]
