### QnA

* Midterm exam : 4월 15일(월) (예정)

문제풀이 + $\alpha$

* 데이터베이스의 정의와 네 가지 데이터 정의 : 공유 / 통합 / 저장 / 운영

* 데이터베이스의 네 가지 특징 : 동시 공유 / 실시간 접근성 / 내용 기반 참조 / 계속 변화

* 범주형 데이터에서 성별은 (명목)형이며, 학점은 (순서)형이다. : 명목 / 순서 / 이산 / 연속

* 파일의 구조가 바뀌면 응용프로그램도 함께 변경해야 한다면 이는 데이터의 (무결성)에 문제가 있다고 할 수 있다. : 무결성의 개념, 데이터베이스 관리 시스템 유지 및 운영의 지속성을 확보하기 위한 모든 것들

* 사용자의 요구에 따라 데이터에 접근하고, 삽입/삭제/수정/검색을 위한 데이터 언어를 데이터(조작어)라고 한다. : 데이터 정의어 / 데이터 조작어 / 데이터 제어어

* 데이터베이스 관리시스템은 (데이터 독립성 유지, 데이터 중복성 회피)라는 장점과, (중앙집중적 시스템에 의한 취약점 존재, 시스템 장애 원인 파악과 백업이 어려워 회복이 곤란)하다는 단점이 있다. : 일부 마비 -> 전체 업무 중단

* 대체로 4단계로 구분되는 DBMS에 현재도 많이 쓰이는 관계 DBMS는 (2)단계에 해당한다. : 관계 DBMS의 단계

* 객체 성격과 관계 성격을 동반한 (개체-관계) DBMS가 존재하며 이는 일반적으로 3단계의 형태로 구성된다.

* Non(SQL) DBMS는 (SQL)을 사용하지 않는 DBMS로 관계 DBMS와 기본 철학이 다르다. : CAP중 Partitional Tolerance를 중시

* 메타 데이터는 1)데이터 관리 시스템이 생성하고, 2)일반 이용자는 검색만 가능하며, 같은 의미로는 시스템 데이터베이스, 데이터 사전 또는 시스템 (카탈로그)가 있다. : 메타데이터에 대한 표현, 데이터 사전 / 카탈로그

* 데이터베이스의 스키마를 정의-변경-삭제하는 데이터 언어를 데이터 (정의어)라고 한다. : 제이터 정의어 - 조작어 - 제어어

* 데이터 모델링은 크게 (연산), 데이터 구조, 그리고 제약조건으로 구성된다. : 데이터 모델링의 구성

* 개체의 특성을 (속성)이라 하며, 속성이 실제 값을 가지면 개체 (인스턴스)가 된다. : E-R 모델에서의 명칭

* 속성은 일반적으로 의미있는 데이터의 가장 작은 (논리적) 단위이다. : 속성의 원자성

* 속성은 단일값/다중값, 단순/복합, (유도) 속성으로 나뉜다.

* 개체-관계 다이어그램에서 개체는 사각형, 관계는 (다이아몬드), 속성은 원으로 표시하며, 개체가 여러 개의 속성을 가진다는 것은 개체-관계 다이어그램에서 여러 개의 (원)을 가진다는 의미이다.

* 아직 결정되지 않았거나 모르는 값을 (NULL)값이라고 한다. : NULL값의 정의

* 관게는 일대일 관계만을 고려하지 않고 (일대다) 관계와 (다대다) 관계를 고려하게 된다. 또한 관계에서 종속성이 존재한다면 이를 (이중) 마름모선으로 표시한다. : 유도속성, 종속관계 성립 시

* 고객이 반드시 구매를 하는 상황이라면 고객과 구매는 종속이지만 구매할 책이 존재하지 않는다면 구매와 책은 (종속)이 아니다. : 구매를 해야만 책이 있는 것은 아님, 고객은 구매를 했으니까 존재함.

* 개체-관계 다이어그램은 데이터베이스에 저장될 파일의 (스키마)에 대한 정보를 줄 수 있다. : 스키마의 이름을 담고 있음

* 개체는 반드시 (물리적) 실체일 필요는 없으며, 개념적 정의 사용이 가능하다. : 물리적 / 개념적 -> entity

* 데이터 모델링은 크게 개념 모델링과 (논리) 모델링이 있다. : 전체 구조를 잡는 모델링

* 릴레이션은 여러 개 존재할 수 있으며 각각의 릴레이션은 릴레이션 이름 (속성) 이름들로 구별된다. : 개체와 속성으로 값이 나뉘어지니까

* 튜플의 유일성은 속성의 부분집합인 키로 구별되며, 이때 사용될 수 있는 키는 (슈퍼키), (후보키), (기본키)가 있다. : + 대체키

* 기본키는 (NULL)값을 가질 수 없으나, (외래)키는 (NULL)값을 가질 수 있다. : 아직 결정되지 않았거나 모르는 값. 개체 무결성 제약

* 기본키와 외래키는 (도메인)이 같아야 하며, 만약에 기본키 중 특정값이 삭제된다면 그 값에 해당하는 외래키 값에 널값을 넣거나 해당 (튜플)을 삭제해야 한다. : 참조 무결성 제약

* 관계 데이터의 무결성을 위해서는 기본키가 (NULL)값을 가지면 안되며, 이를 위해서 (NULL)값에 대한 입력 자체를 제한해야 한다.

* (참조 무결성) 제약조건은 외래키의 도메인과 기본키의 도메인을 일치시켜야 하는 제약조건이다.

* 릴레이션에서 차수는 (속성의 개수)를 카디널리티는 (튜플의 개수)를 의미한다. : 속성의 증가는 복잡도를 증가시키므로 차수, 튜플은 원소의 값이므로 카디널리티

* 만약의 외래키의 값을 ()하는 경우 참조 무결성 제약조건에 영향을 주게 된다. : 변경, 삭제, 추가 등등

`-` OX

* 비정형 데이터는 수치화가 불가능한 데이터이다. X : 컴퓨터로 읽어와야 하므로 무조건 수치화가 이루어짐

* 비정형 데이터는 다차원 배열 / 텐서를 이용해서 표현이 가능한 경우가 많으며, 그 길이나 차원이 가변적일 수 있다. O

* 이미지나 음성 데이터는 기본적으로 비정형 데이터로 속성을 정의하기가 쉽다. X : 애초에 비정형 데이터는 속성을 정의하기가 어려움. 둘 중 하나만 맞는 것.

* 비정형 데이터로 데이터베이스를 구축하는 것은 불가능하다. X : Non-SQL DBMS

* 몽고 DB는 key-document 구조의 비정형 데이터베이스이다. O

* 몽고 DB는 컬렉션이 관계 DB의 속성에 해당한다. X : 컬렉션, 다큐먼트, 필드

* 몽고 DB에선 빠른 검색 자체가 불가능하다. O : 비정형 데이터는 어렵다.

* 분산환경 하에 DB는 Consistency, Availability, Partitions Tolerance를 동시에 만족하기 위해서 노력해야 하며, 이를 동시에 만족하는 해가 존재한다. X : CA는 관계형 데이터베이스, P는 분산환경의 비정형 데이터베이스에 초점을 맞춘다. 일관성과 분할 작동은 공존하기 어렵다.

`-` 연산

|번호|이름|나이|
|-|-|-|
|1|김민서|30|
|2|이나영|25|

|번호|이름|나이|
|-|-|-|
|1|김민서|30|
|4|이철희|27|

* 오른쪽과 왼쪽 릴레이션에 대한 합집합과 교집합을 구하시오.(교집합을 G라 명명)
> 튜플의 개수 : 원소의 개수

|번호|이름|나이|
|-|-|-|
|1|김민서|30|
|2|이나영|25|
|4|이철희|27|

|번호|이름|나이|
|-|-|-|
|1|김민서|30|

* 오른쪽 릴레이션에서 왼쪽 릴레이션에 대한 차집합을 구하시오.

|번호|이름|나이|
|-|-|-|
|2|이나영|25|

|이름|나이|주소|성별|학년|주거형태|
|-|-|-|-|-|-|
|김민서|30|경기|남|4|원룸|
|이나영|25|광주|여|3|기숙사|
|김주형|30|전주|남|3|자택|

* 교집합과 위 릴레이션의 카티션 프로덕트를 구하시오 (H라 명명)
> 차수가 9인 릴레이션이 나옴

|G.번호|G.이름|G.나이|S.이름|S.나이|S.주소|S.성별|S.학년|S.주거형태|
|-|-|-|-|-|-|-|-|-|
|1|김민서|30|김민서|30|경기|남|4|원룸|
|1|김민서|30|이나영|25|광주|여|3|기숙사|
|1|김민서|30|김주형|30|전주|남|3|자택|

* H에서 이름이 겹치는 튜플만 남기기 위한 select 구문을 기술하고, 그 결과를 구하시오.

$$\sigma_{R.이름 = S.이름}(H)$$

|R.번호|R.이름|R.나이|S.이름|S.나이|S.주소|S.성별|S.학년|S.주거형태|
|-|-|-|-|-|-|-|-|-|
|1|김민서|30|김민서|30|경기|남|4|원룸|

각 속성에 대해서 릴레이션의 이름을 붙여 구분하기 편하게 한다. (동등조인)


* 왼쪽 릴레이션에서 번호와 이름만으로 구성된 릴레이션을 구하기 위한 project 구문을 쓰고 이를 구하시오. (K로 명명)

$$\pi_{이름, 번호}(R)$$

* 오른쪽 릴레이션을 K로 division한 결과를 구하시오.

|번호|이름|나이|주소|
|-|-|-|-|
|1|김민서|20|서울|
|2|이나영|30|전주|
|5|김철수|25|경기|

|번호|이름|학년|키|
|-|-|-|-|
|1|김민서|3|167|
|2|이나영|3|158|
|3|김민서|3|180|

* 두 개의 릴레이션에 대한 자연조인에 대한 구문을 쓰고 이를 구하시오. (번호와 이름으로 데이터 보존)
$$R\Join_NS$$

|번호|이름|나이|주소|학년|키|
|-|-|-|-|-|-|
|1|김민서|20|서울|3|167|
|2|이나영|30|전주|3|158|

> 둘 중 하나를 지우는 것, 안지우면 동등조인이고 이름을 달라지게 해야.

* 두 개의 릴레이션에 대한 전체 외부조인의 구문을 쓰고 이를 구하시오.

|번호|이름|나이|주소|학년|키|
|-|-|-|-|-|-|
|1|김민서|20|서울|3|167|
|2|이나영|30|전주|3|158|
|3|김민서|NULL|NULL|3|180|
|5|김철수|25|경기|NULL|NULL|

* 두 개의 릴레이션에 대한 자연조인 (이름으로)

|번호|번호|이름|나이|주소|학년|키|
|-|-|-|-|-|-|-|
|1|1|김민서|20|서울|3|167|
|1|3|김민서|20|서울|4|180|
|2|2|이나영|30|전주|3|158|

> 중복되는 경우 카티션 프로덕트로 나오게 된다. 즉, 왠만해선 조인을 할 때 기본키에 해당하는 것으로 하는 게 좋다.

* 두 개의 릴레이션에 대한 오른쪽 세미조인의 구문을 쓰고 이를 구하시오.

|번호|이름|나이|주소|
|-|-|-|-|
|1|김민서|20|서울|
|2|이나영|30|전주|

* 세타조인 : 속성의 종류로 조인

$$R \Join_{R.ID < S.ID} S$$

> 릴레이션 간 비교를 하기 위한 조인이라고 보면 된다. (일반적인 조인, 조건을 만족하는 것들을 다 붙여야 함)
>
> 그냥 카티션 프로덕트를 먼저 만들어놓고 조건에 해당하는 것만 고르면 된다. (select)

`-` R 코드 리뷰

R은 기본적으로 벡터의 형식으로 자료를 저장한다.

In [7]:
## 논리연산자
print(1 < 5 && 5 > 3)  ## 그냥 &, |는 bool이 저장된 벡터간 논리연산을 한다.
print(1 > 3 || 5 > 3)

[1] TRUE
[1] TRUE


In [12]:
## 자료형
mode(data.frame(x = 1, y = 2))  ## data formation
class(data.frame(x = 1, y = 2)) ## data resourse

[1] "list"

[1] "data.frame"

In [13]:
## operation with two vector differnt length
1:3 + 1:40  ## times short vector

Warning message in 1:3 + 1:40:
“longer object length is not a multiple of shorter object length”


[1]  2  4  6  5  7  9  8 10 12 11 13 15 14 16 18 17 19 21 20 22 24 23 25 27 26
[26] 28 30 29 31 33 32 34 36 35 37 39 38 40 42 41

In [20]:
## multy variable assign
a = c(1,2,3)
a[which(a >= 2)] = 0
a

[1] 1 0 0

In [22]:
## array
print(array(1:12, c(2,2,3)))

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12



> 파이썬은 뒤 두개가 행, 열인데 여기는 수학적으로 생각함(스택의 개념이 아님). 그리고 행렬 구조를 유지하고자 함

In [23]:
## Uniqueness of tuple
data.frame(a = c(1,1,2,3), b = c(2,2,3,5)) |> unique()

a b
1 1 2
3 2 3
4 3 5

> 튜플의 유일성을 확보해주는 함수. 시리즈(벡터)에 적용하면 중복되지 않은 값이 몇개인지 알 수 있겠지...

In [27]:
## merge : expansion of join
cust_mart_7 <- data.frame(cust_id = c("c03", "c04", "c05", "c06"), buy_cnt = c(3,1,4,1))
cust_mart_6 <- data.frame(cust_id = c("c04", "c05", "c06", "c07"), buy_cnt = c(3,2,1,3))

merge(cust_mart_6, cust_mart_7, by = 'cust_id')  ## Natural join
merge(cust_mart_6, cust_mart_7, by = 'cust_id', all.x = TRUE)  ## left outer join
merge(cust_mart_6, cust_mart_7, by = 'cust_id', all.y = TRUE)  ## right outer join
merge(cust_mart_6, cust_mart_7, by = 'cust_id', all.x = TRUE, all.y = TRUE)  ## total outer join

cust_id buy_cnt.x buy_cnt.y
1 c04     3         1        
2 c05     2         4        
3 c06     1         1

cust_id buy_cnt.x buy_cnt.y
1 c04     3          1       
2 c05     2          4       
3 c06     1          1       
4 c07     3         NA

cust_id buy_cnt.x buy_cnt.y
1 c03     NA        3        
2 c04      3        1        
3 c05      2        4        
4 c06      1        1

cust_id buy_cnt.x buy_cnt.y
1 c03     NA         3       
2 c04      3         1       
3 c05      2         4       
4 c06      1         1       
5 c07      3        NA

In [30]:
a = strsplit('abc', "")  ## split. list object
paste(a[[1]], collapse = "")  ## +. sep = "" -> object saved by seperate vector

[1] "abc"

In [34]:
nchar('abc')  ## number of character

[1] 3

In [35]:
f = c('toy toy', 'told', 'tall')
gsub('t', 'k', f)  ## substitude, 대체함.
sub('t', 'k', f)  ## apply only first word

[1] "koy koy" "kold"    "kall"

[1] "koy toy" "kold"    "kall"

In [ ]:
A = rnorm(100)
aa = data.frame(a = rnorm(100), b = rpois(100, a))  ## 이게 되네

write.table(file = "s.txt", aa)  ## 데이터프레임을 파일로 저장함
a = read.table(file = "s.txt")  ## 테이블 데이터를 읽음
write.csv(file = "s.csv", a)  ## csv파일로 저장하면 인덱스 열을 추가적으로 저장하여 삭제가 필요

In [ ]:
## 엑셀 파일 읽기
install.packages("readxl")
library(readxl)
read_excel("file name", sheet, na = "")  ## sheet : 번호나 이름, na = 결측치 인식

In [ ]:
## saving working space environment
v = array(1:40, c(2,2,10))
save(file = "s.Rdata", aa, v)
load("s.Rdata")  ## 작업공간에 불러옴

In [ ]:
## listing package function and data
ls(package:packagename)

In [37]:
## function
sq_ <- function(a) {
    a = a^2  ## local declaraion
    return(a)
}
sq_x <- function(a) {
    x <<- a^2  ## global declaration, not retuen function
}

In [39]:
sq_(2)
sq_x(2)
x

[1] 4

[1] 4

In [40]:
## dplyr
library(dplyr)


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [ ]:
filter(data.frame, colname == "asdf")  ## select. 비교식을 적어놓음.
select(data.frame, colnames, ends_with("end words"), contains("char"))  ## project. 선택할 열 이름을 적음. ends_with, contains는 여기서만 사용 가능
mutate(data.frame, colnames operation)  ## assign(df.apply(function)), you can assign new column for operation other columns value
arrange(data.frame, desc(colname))  ## arrange(colname) : ascending. sort_value() in R
group_by(data.frame, colnames) %>% sumarise(col1 = n(), col2 = mean(col2, na.rm = TRUE))  ## make a groups and operate each groups
distinct(data.frame, colname, .keep_all = TRUE)  ## each, unique. processing duplication. and keep another columns.

In [ ]:
## operation in a chain
df |> filter(conditions) |> select(colnames or ends_with()) ...

In [ ]:
## normal dataset operater
union(d1, d2)  ## union
intersect(d1, d2)  ## intersection
setdiff(d1, d2)  ## difference of sets
expand(df1, df2, nesting(columns))  ## cartesian product

In [ ]:
## pure relationship operater
inner_join(df1, df2, by = "colname")  ## merge(df1, df2, by = "")
full_join(df1, df2, by = "colname")  ## merge(df1, df2, by = "", all.x = TRUE, all.y = TRUE)
right_join(df1, df2, by = "colname")  ## merge(df1, df2, by = "", all.y = TRUE)
left_join(df1, df2, by = "colname")  ## merge(df1, df2, by = "", all.x = TRUE)